projects/forms/src/lib/validators/decimals-after-comma/decimals-after-comma.validator.spec.ts, projects/forms/src/lib/validators/decimals-after-comma/decimals-after-comma.validator.ts, projects/forms/src/lib/validators/validators.ts
With this validator we can check the amount of decimals are inputted after a comma. This validator is useful in cases where you want your users to fill in an amount of money.
=>  feat(forms): Add a decimals-after-comma-validator - ngx-forms

package-lock.json, package.json, projects/forms/package.json, projects/forms/src/lib/validators/chronological-dates/chronological-dates.validator.spec.ts, projects/forms/src/lib/validators/chronological-dates/chronological-dates.validator.ts, projects/forms/src/lib/validators/validators.ts
Adds a FormGroup validator to check if two dates are in chronological order. Ideal for when you have a start and end date in a form.
=> feat(forms): Add chronological dates validator - ngx-forms

projects/table/README.md
Fixed small typo in the example of the custom cell.
=> fix(readme): update readme of table project

projects/table-test/src/app/app.component.html, projects/table-test/src/app/app.component.ts, projects/table-test/src/app/app.module.ts, projects/table/package.json, projects/table/src/lib/table/ngx-table.component.html, projects/table/src/lib/table/ngx-table.component.ts
Fixes these two issues:
1. writeValue didn't function correctly as it was comparing to the incorrect value
2. Both the checkbox and the radiobutton were visible when selectType was set to checkbox
=> fix(table): Fix incorrect checkbox handling and incorrect writeValue handling

projects/utils/package.json, projects/utils/src/lib/pipes/clean-array/clean-array.pipe.md, projects/utils/src/lib/pipes/clean-array/clean-array.pipe.spec.ts, projects/utils/src/lib/pipes/clean-array/clean-array.pipe.ts, projects/utils/src/lib/pipes/entries/entries.pipe.spec.ts, projects/utils/src/lib/pipes/index.ts
A pipe was added to filter the falsy values from an array. The falsy values to be retained can be specified.
=> feat(clean-array): add clean array pipe

projects/table-test/src/app/app.component.html, projects/table/package.json, projects/table/src/lib/cell/cell.directive.ts, projects/table/src/lib/interfaces/internal-helpers.ts, projects/table/src/lib/interfaces/show-header-requirements.ts, projects/table/src/lib/table/ngx-table.component.html, projects/table/src/lib/table/ngx-table.component.ts
Adds an input so we can add cypress tags directly to a cell in the table.
=> feat(ngx-table): Add input for cypress tags

projects/store-test/src/app/app.component.ts, projects/store-test/src/store/user.store.ts, projects/store/package.json, projects/store/src/lib/store/interfaces/index.ts, projects/store/src/lib/store/interfaces/store-assets-generator-options.ts, projects/store/src/lib/store/interfaces/store-generator.ts, projects/store/src/lib/store/utils/base-store/base-store.util.spec.ts, projects/store/src/lib/store/utils/base-store/base-store.util.ts, projects/store/src/lib/store/utils/entity-store/entity-adapter.util.spec.ts, projects/store/src/lib/store/utils/entity-store/entity-adapter.util.ts, projects/store/src/lib/store/utils/store-generator.util/store-generator.util.ts
Op vraag van gebruikers van de store utils werd nu ook een initialValue voorzien bij de asset generators.
=> feat(ngx-store): Add option to add initialValue to the generators

projects/forms/README.md, projects/forms/package.json, projects/forms/src/lib/abstracts/index.ts, projects/forms/src/lib/abstracts/save-on-exit/index.ts, projects/forms/src/lib/abstracts/save-on-exit/save-on-exit.component.abstract.ts, projects/forms/src/lib/abstracts/save-on-exit/save-on-exit.service.abstract.ts, projects/forms/src/lib/guards/index.ts, projects/forms/src/lib/guards/save-on-exit/save-on-exit.guard.ts, projects/forms/src/public-api.ts
Een herbruikbaar en configureerbaar save-on-exit mechanisme voor componenten met forms.
=> feat(ngx-forms): Add save-on-exit mechanism

projects/form-test/src/date-input/date-input.component.ts, projects/form-test/src/depended-dates/depended-dates.component.ts, projects/form-test/src/form-accessor/form-accessor.component.ts, projects/forms/README.md, projects/forms/package.json, projects/forms/src/lib/utils/accessor-providers/accessor-providers.util.ts, projects/forms/src/lib/utils/index.ts
Adds a util to create the AccessorProviders, significantly reducing the amount of overhead.
=> feat(ngx-forms): Add createAccessorProviders util

apps/i18n-test/src/app/app-routing.module.ts, apps/i18n-test/src/app/app.module.ts, libs/i18n/package.json, libs/i18n/src/lib/guards/i18n/i18n.guard.spec.ts, libs/i18n/src/lib/guards/i18n/i18n.guard.ts, libs/i18n/src/lib/services/i18n/i18n.service.spec.ts, libs/i18n/src/lib/services/i18n/i18n.service.ts
Routing to a different available language was not possible due to incorrect use of the available languages and current language fetching.
=> fix(i18n): Fix issue with i18nGuard and currentLanguage

README.md, libs/cookies/README.md, libs/forms/README.md, libs/i18n/README.md, libs/layout/README.md, libs/layout/package.json, libs/store/README.md, libs/table/README.md, libs/utils/README.md, package.json
- Updates the package documentation to create a uniform look and feel
- Adds version information
- Moves author/contributors information to the ngx-tools readme (as the entire team helps with the process)
=> feat(ngx-tools): Update documentation to create a uniform look and feel

apps/layout-test/.eslintrc.json, apps/layout-test/src/app/app.component.html, apps/layout-test/src/app/app.component.ts, apps/layout-test/src/app/app.config.ts, apps/layout-test/src/display-content/error.component.ts, apps/layout-test/src/display-content/index.ts, apps/layout-test/src/display-content/loading.component.ts, apps/layout-test/src/display-content/offline.component.ts, libs/layout/.eslintrc.json, libs/layout/README.md, libs/layout/src/lib/abstracts/display-content/display-content.component.ts, libs/layout/src/lib/abstracts/index.ts, libs/layout/src/lib/directives/display-content/components/display-content-test.component.ts, libs/layout/src/lib/directives/display-content/display-content.directive.spec.ts, libs/layout/src/lib/directives/display-content/display-content.directive.ts, libs/layout/src/lib/directives/index.ts, libs/layout/src/lib/providers/display-content/display-content.provider.ts, libs/layout/src/lib/providers/index.ts, libs/layout/src/lib/services/index.ts, libs/layout/src/lib/services/online-service/online.service.ts, libs/layout/src/lib/tokens/display-content-configuration.token.ts, libs/layout/src/lib/tokens/index.ts, libs/layout/src/lib/types/display-content.types.ts, libs/layout/src/lib/types/index.ts, libs/layout/src/public-api.ts
Adds a directive that can provide a default fallback for loading, error and offline states.
Input on other possible states is always appreciated!
=> feat(ngx-layout): Add displayContent directive

libs/tour/src/lib/services/tour-service/tour.service.ts
Using the CDK block scrolling strategy with elements that are currently not in view makes it so that the strategy sets the left and top position of the main HTML tag. However, this can cause issues with the positioning of your application, and does not restore correctly afterwards.
This PR uses a custom approach to blocking the scrolling, which removes the issue all together.
=> fix(ngx-layout): Handle scroll disabling ourselves instead of using the CDK strategy

libs/cookies/package.json, libs/forms/package.json, libs/i18n/package.json, libs/layout/package.json, libs/store/package.json, libs/table/package.json, libs/tour/package.json, libs/utils/package.json
As mentioned in the Angular discord, we got the recommendation to update our package.json files with more information. This PR does that.
=> feat(meta): Updates all meta data of all packages

libs/inform/.eslintrc.json, libs/inform/jest.config.ts, libs/inform/ng-package.json, libs/inform/package.json, libs/inform/project.json, libs/inform/src/test-setup.ts, libs/inform/tsconfig.json, libs/inform/tsconfig.lib.json, libs/inform/tsconfig.lib.prod.json, libs/inform/tsconfig.spec.json, tsconfig.base.json
Setup for the `ngx-inform` package, which will be the home for tooltips, toasts and snackbars.
=> feat(ngx-inform): Setup ngx-inform package

apps/layout-test/src/app/app.config.ts, apps/layout-test/src/pages/main/main.component.html, apps/layout-test/src/pages/main/main.component.ts, apps/layout-test/src/tooltip/tooltip.component.scss, apps/layout-test/src/tooltip/tooltip.component.ts, libs/inform/README.md, libs/inform/src/index.ts, libs/inform/src/lib/abstracts/index.ts, libs/inform/src/lib/abstracts/tooltip/tooltip.abstract.component.ts, libs/inform/src/lib/directives/index.ts, libs/inform/src/lib/directives/tooltip/tooltip.directive.ts, libs/inform/src/lib/index.ts, libs/inform/src/lib/providers/index.ts, libs/inform/src/lib/providers/tooltip/tooltip-configuration.provider.ts, libs/inform/src/lib/services/index.ts, libs/inform/src/lib/services/tooltip-service/tooltip.service.spec.ts, libs/inform/src/lib/services/tooltip-service/tooltip.service.ts, libs/inform/src/lib/tokens/index.ts, libs/inform/src/lib/tokens/tooltip/tooltip-configuration.token.ts, libs/inform/src/lib/types/index.ts, libs/inform/src/lib/types/tooltip.types.ts, libs/inform/src/test-setup.ts, libs/utils/src/lib/pipes/index.ts, tsconfig.base.json
=> feat(ngx-layout): Add NgxTooltipDirective

apps/layout-test/src/pages/main/main.component.html, apps/layout-test/src/pages/main/main.component.scss, libs/inform/src/lib/abstracts/tooltip/tooltip.abstract.component.ts, libs/inform/src/lib/directives/tooltip/tooltip.directive.ts, libs/inform/src/lib/services/tooltip-service/tooltip.service.spec.ts, libs/inform/src/lib/services/tooltip-service/tooltip.service.ts, libs/inform/src/lib/types/tooltip.types.ts
=> fix(tooltip): Allow moving between tooltips when they're stacked

apps/layout-test/src/app/app.component.html, apps/layout-test/src/app/app.component.ts, apps/layout-test/src/styles.scss, libs/layout/README.md, libs/layout/package.json, libs/layout/src/lib/components/accordion/accordion.component.ts, libs/layout/src/lib/components/accordion/index.ts, libs/layout/src/lib/components/accordion/item/accordion-item.component.html, libs/layout/src/lib/components/accordion/item/accordion-item.component.scss, libs/layout/src/lib/components/accordion/item/accordion-item.component.ts, libs/layout/src/lib/components/index.ts, libs/layout/src/lib/types/accordion.types.ts, libs/layout/src/lib/types/index.ts
=> feat(ngx-layout): Add accordion component

libs/angular/tour/package.json
Bump the package version in preparation for release.
Not applicable
=> build(ngx-tour):v18.5.0

apps/docs/project.json, apps/docs/src/app/app.component.ts, apps/docs/src/app/pages/landing/landing-page.component.ts, libs/angular/layout/src/lib/components/accordion/accordion.component.ts, libs/angular/layout/src/lib/components/configurable-layout/configurable-layout.component.ts
- Increase docs bundle size threshold
- Remove unused imports
=> fix(build): resolve generic build "errors" and apply linting in multiple libs

libs/angular/tour/src/lib/services/tour-service/tour-server.spec.ts, libs/angular/tour/src/lib/services/tour-service/tour.service.spec.ts
=> fix(ngx-tour): Fix broken test

libs/nodejs/testing/.eslintrc.json, libs/nodejs/testing/README.md, libs/nodejs/testing/docs/factories/early-return-empty-array-value/early-return-empty-array-value.md, libs/nodejs/testing/docs/factories/early-return-on-falsy-value/early-return-on-falsy-value.md, libs/nodejs/testing/jest.config.ts, libs/nodejs/testing/package-lock.json, libs/nodejs/testing/package.json, libs/nodejs/testing/project.json, libs/nodejs/testing/src/index.ts, libs/nodejs/testing/src/lib/factories/early-return-empty-array-value/early-return-empty-array-value.spec.ts, libs/nodejs/testing/src/lib/factories/early-return-empty-array-value/early-return-empty-array-value.ts, libs/nodejs/testing/src/lib/factories/early-return-on-falsy-value/early-return-on-falsy-value.spec.ts, libs/nodejs/testing/src/lib/factories/early-return-on-falsy-value/early-return-on-falsy-value.ts, libs/nodejs/testing/src/lib/factories/index.ts, libs/nodejs/testing/tsconfig.json, libs/nodejs/testing/tsconfig.lib.json, libs/nodejs/testing/tsconfig.spec.json, libs/nodejs/testing/vite.config.ts, tsconfig.base.json
Move node-testing package to monorepo
=> feat(node-testing): Move node-testing package to monorepo

libs/angular/core/.eslintrc.json, libs/angular/core/README.md, libs/angular/core/jest.config.ts, libs/angular/core/ng-package.json, libs/angular/core/package.json, libs/angular/core/project.json, libs/angular/core/src/index.ts, libs/angular/core/src/lib/services/index.ts, libs/angular/core/src/lib/services/window/window.service.md, libs/angular/core/src/lib/services/window/window.service.mock.ts, libs/angular/core/src/lib/services/window/window.service.spec.ts, libs/angular/core/src/lib/services/window/window.service.ts, libs/angular/core/src/test-setup.ts, libs/angular/core/tsconfig.json, libs/angular/core/tsconfig.lib.json, libs/angular/core/tsconfig.lib.prod.json, libs/angular/core/tsconfig.spec.json, tsconfig.base.json
Sets up the ngx-core package and adds the NgxWindowService
=> feat(ngx-core): Setup core package

libs/angular/core/package.json
=> build(ngx-core):v19.0.0 

apps/docs/src/app/categories/javascript/index.ts, apps/docs/src/app/categories/javascript/utils/sub-categories/number/ng-doc.category.ts, apps/docs/src/app/pages/docs/javascript/utils/file/openFile/index.md, apps/docs/src/app/pages/docs/javascript/utils/introduction/index.md, apps/docs/src/app/pages/docs/javascript/utils/number/inRange/index.md, apps/docs/src/app/pages/docs/javascript/utils/number/inRange/ng-doc.page.ts, libs/javascript/utils/src/lib/number/in-range/in-range.util.md, libs/javascript/utils/src/lib/number/in-range/in-range.util.spec.ts, libs/javascript/utils/src/lib/number/in-range/in-range.util.ts
Add inRange number util + documentation
_Attach a video/screenshot/other attachment if necessary_
=> feature: Add inRange number util + documentation

apps/docs/src/app/pages/docs/javascript/utils/introduction/index.md, apps/docs/src/app/pages/docs/javascript/utils/object/search-recursively/index.md, apps/docs/src/app/pages/docs/javascript/utils/object/search-recursively/ng-doc.page.ts, libs/javascript/utils/src/lib/object/index.ts, libs/javascript/utils/src/lib/object/search-recursively/search-recursively.util.md, libs/javascript/utils/src/lib/object/search-recursively/search-recursively.util.spec.ts, libs/javascript/utils/src/lib/object/search-recursively/search-recursively.util.ts
Add search recursively util to javascript utils
_Attach a video/screenshot/other attachment if necessary_
=> feature: Add search recursively util + documentation

apps/docs/src/app/pages/docs/angular/forms/introduction/index.md
Updates the introduction page with information for business and developers.
=> documentation(ngx-forms): Update introduction documentation

apps/docs/src/app/categories/angular/index.ts, apps/docs/src/app/categories/angular/utils/sub-categories/utils/ng-doc.category.ts, apps/docs/src/app/pages/docs/angular/utils/utils/simple-changes/index.md, apps/docs/src/app/pages/docs/angular/utils/utils/simple-changes/ng-doc.page.ts, libs/angular/utils/src/lib/utils/simple-changes/simple-changes.util.md, libs/angular/utils/src/lib/utils/simple-changes/simple-changes.util.spec.ts, libs/angular/utils/src/lib/utils/simple-changes/simple-changes.util.ts
Add util to check whether or not a SimpleChanges property has changed
_Attach a video/screenshot/other attachment if necessary_
=> feature: add SimpleChangesHasChanged util

apps/docs/src/app/pages/docs/angular/utils/installation/index.md, libs/angular/utils/src/lib/utils/index.ts, libs/angular/utils/src/public-api.ts
Add simpleChangeHasChanged to public API and installation docs for ngx-utils
_Attach a video/screenshot/other attachment if necessary_
=> chore: add utils to installation page to ngx-utils

libs/angular/core/src/index.ts, libs/angular/core/src/lib/utils/index.ts, libs/angular/core/src/lib/utils/simple-changes/simple-changes.util.md, libs/angular/core/src/lib/utils/simple-changes/simple-changes.util.spec.ts, libs/angular/core/src/lib/utils/simple-changes/simple-changes.util.ts, tsconfig.base.json
Move simpleChangesUtil to core
=> feat(ngx-core): Move simple-changes util to ngx-core

libs/angular/core/package.json
=> build(ngx-core):v19.1.0

libs/angular/layout/package.json
=> build(ngx-layout):v19.1.0

libs/angular/layout/package.json
=> build(ngx-layout):v19.2.0

.eslintrc.json, apps/cookies-test/project.json, apps/docs/project.json, apps/form-test/project.json, apps/i18n-test/project.json, apps/layout-test/project.json, apps/store-test/project.json, apps/table-test/project.json
Adds module boundaries to avoid issues of incorrect imports in the future.
=> feat(setup): Add module boundaries

libs/javascript/types/auth/package.json
Release `@studiohyperdrive/types-auth`
=> build(js-types-auth):v1.0.0

libs/javascript/types/auth/package.json
New release of `@studiohyperdrive/types-auth`
=> build(js-types-auth):v2.0.0

libs/javascript/utils/package.json
Release the new version with the updated vite peer-dependency
=> build(studiohyperdrive/utils):v2.0.1

apps/docs/src/app/pages/landing/landing-page.component.html
Updating the home page with the updated texts
=> feat(documentation): Update documentation landing page

apps/docs/src/app/pages/docs/angular/layout/introduction/demos/accordion/accordion.component.html, apps/docs/src/app/pages/docs/angular/layout/introduction/demos/accordion/accordion.component.scss, apps/docs/src/app/pages/docs/angular/layout/introduction/demos/accordion/accordion.component.ts, apps/docs/src/app/pages/docs/angular/layout/introduction/demos/annotation/annotation.component.html, apps/docs/src/app/pages/docs/angular/layout/introduction/demos/annotation/annotation.component.scss, apps/docs/src/app/pages/docs/angular/layout/introduction/demos/annotation/annotation.component.ts, apps/docs/src/app/pages/docs/angular/layout/introduction/demos/data.demo.ts, apps/docs/src/app/pages/docs/angular/layout/introduction/demos/index.ts, apps/docs/src/app/pages/docs/angular/layout/introduction/demos/offline/offline.component.ts, apps/docs/src/app/pages/docs/angular/layout/introduction/index.md, apps/docs/src/app/pages/docs/angular/layout/introduction/ng-doc.page.ts, apps/docs/src/app/pages/docs/angular/table/introduction/index.md
Updates the introduction page to match our new format.
=> documentation(ngx-layout): Update introduction page

libs/angular/table/package.json
=> build(ngx-table):v19.0.1

libs/angular/authentication/package.json
=> build(ngx-auth):v19.0.0

README.md
This way it's easier to find the link to the docs than the link in the sidebar in my opinion. Most packages link their docs this way and is probably the way most people look for the docs. 
=> feat(readme): added a link to the docs in the repo

libs/angular/i18n/package.json
=> build(ngx-i18n):v19.1.0

libs/angular/authentication/src/lib/services/authenticated-http-client/authenticated-http-client.service.ts
=> fix(ngx-auth): Fix incorrect obj-clean import

libs/angular/utils/package.json
=> build(ngx-utils):v19.0.1

libs/angular/gov/flanders/package.json
=> build(ngx-gov-flanders):v19.0.0

libs/angular/store/package.json
=> build(ngx-store):v19.2.0

libs/angular/store/package.json
=> build(ngx-store):v19.3.0
