projects/utils/package-lock.json, projects/utils/package.json, projects/utils/src/lib/window-service/window.service.mock.ts, projects/utils/src/lib/window-service/window.service.spec.ts, projects/utils/src/lib/window-service/window.service.ts
When using the windowService in a project I noticed that I could just push a new value to the `width$`, whilst that property should only be updated when the window resizes, and I as a user should not be able to push anything on it.
I went through the code and saw that the BehaviorSubjects were public, so I made those private and returned the needed values as Observables. I also added an Observable for the current scroll position, which seemed useful to me when we for instance want to start loading specific content at specific scroll positions.
While I was at it, I added some TSDoc so that the doc in the readme would also be available in VSCode
Finally I noticed the test weren't working so I fixed those as well.
=> feat(windowservice): Made the windowService subjects private, added TSDoc and fix tests

projects/forms/src/lib/validators/validators.ts, projects/forms/src/public-api.ts
I did a quick test with the Validators class object in Stackblitz and noticed that then I had to `import as` if I wanted to use our validators and the default Angular validators.
To make sure that it does not become an issue in the future, I've renamed it to NgxValidators.
=> feat(forms): Update name of Validators class - ngx-forms

projects/forms/src/lib/validators/depended-required/depended-required.validator.spec.ts, projects/forms/src/lib/validators/depended-required/depended-required.validator.ts, projects/forms/src/lib/validators/email/extended-email.validator.spec.ts, projects/forms/src/lib/validators/validators.ts
Adds a FormGroup validator to validate if a set of controls are required in case a different control has been filled in. By default it checks on whether the control's value is filled in, but a specific match function can be provided in case a set of controls becomes required once a certain option is selected.
=> feat(forms): Add depended required validator - ngx-forms

projects/store/package-lock.json, projects/store/package.json, projects/store/src/lib/store/interfaces/index.ts, projects/store/src/lib/store/interfaces/store-generator.ts, projects/store/src/lib/store/utils/store-generator.util/store-generator.util.ts, projects/store/src/public-api.ts
The current implementation allowed for a selectId function, but did not allow us to pass it onto the generator. This PR fixes this issue and also exports a few needed interfaces.
=> feat(ngx-store): Export remaining needed interfaces and add ability to pass a selectId function - ngx-store

projects/i18n/README.md, projects/utils/README.md, projects/utils/package-lock.json, projects/utils/package.json, projects/utils/src/lib/pipes/index.ts, projects/utils/src/lib/pipes/with-router-links/with-router-links.config.ts, projects/utils/src/lib/pipes/with-router-links/with-router-links.md, projects/utils/src/lib/pipes/with-router-links/with-router-links.pipe.spec.ts, projects/utils/src/lib/pipes/with-router-links/with-router-links.pipe.ts, projects/utils/src/lib/pipes/with-router-links/with-router-links.types.ts, projects/utils/src/lib/utils.const.ts, projects/utils/src/lib/utils.types.ts
This PR adds a pipe that is able to find and replace in-text anchors with a web component that wraps around a router-link.
For more info check the README.
=> feat(utils): added withRouterLinksPipe to allow for in-text router-link conversion

projects/table-test/src/app/app.component.html, projects/table-test/src/app/app.component.ts, projects/table-test/src/app/app.module.ts, projects/table/package.json, projects/table/src/lib/table/ngx-table.component.ts
The open row state was shown even when no detail row was provided. This should fix this issue.
=> fix(ngx-table): Don't show open row state if no detail row is provided

projects/utils/package.json, projects/utils/src/lib/pipes/index.ts, projects/utils/src/lib/pipes/log/log.pipe.md, projects/utils/src/lib/pipes/log/log.pipe.ts
Mainly for debugging, this pipe logs the provided value to the console, not the page.
=> feat(log): add logpipe for debugging

projects/utils/package-lock.json, projects/utils/package.json, projects/utils/src/lib/pipes/strip-html/strip-html.pipe.spec.ts, projects/utils/src/lib/pipes/strip-html/strip-html.pipe.ts
A change to the stripHTML pipe that I've tried out a while ago but never actually needed (scope change).
Since I've built it, might be good to actually release it so that others can use it.
=> bugfix(ngx-utils): The stripHtml pipe now has an optional 'replaceWith' argument

projects/forms/package-lock.json, projects/forms/package.json, projects/forms/src/lib/validators/email/extended-email.validator.ts
The email validator regex was too restrictive which caused it to fail on:
- TLDs that were longer than four characters (eg. `.design`).
- Cased emailaddresses, which is common in office365 managed organisations
=> bugfix(ngx-forms): The email validator is now case insensitive and allows for longer TLDs

projects/layout-test/src/app/app.component.html, projects/layout-test/src/app/app.component.scss, projects/layout/README.md, projects/layout/package.json, projects/layout/src/lib/components/configurable-layout/configurable-layout.component.html, projects/layout/src/lib/components/configurable-layout/configurable-layout.component.scss, projects/layout/src/lib/components/configurable-layout/configurable-layout.component.ts
Before, the equal sizing did not allow items to be of equal size in height. This is unexpected behavior, as the grid suggests that all items will be of equal size.
Before:
After:
To allow for better styling, this PR also introduces the rowGap and the columnGap properties.
=> fix(ngx-layout): Fix styling issues with equal sizing

projects/layout-test/src/app/app.component.html, projects/layout-test/src/app/app.component.scss, projects/layout-test/src/app/app.component.ts, projects/layout/README.md, projects/layout/package.json, projects/layout/src/lib/components/configurable-layout/configurable-layout.component.html, projects/layout/src/lib/components/configurable-layout/configurable-layout.component.scss, projects/layout/src/lib/components/configurable-layout/configurable-layout.component.ts, projects/layout/src/lib/pipes/item-size/item-size.pipe.ts, projects/layout/src/lib/types/configurable-layout.ts
Updates the ngx-layout package so that the configurable layout now has two options, `static` or `editable`.
=> feat(ngx-layout): Make the ngx-configurable-layout editable by the end-user

projects/layout-test/src/app/app.component.ts, projects/layout/package.json, projects/layout/src/lib/components/configurable-layout/configurable-layout.component.ts
When the form gets patched after the initial writeValue, the form emitted unnecessarily.  This should be fixed.
=> fix(ngx-layout): Fix unnecessary emits in the ngx-configurable-layout

projects/forms/README.md, projects/forms/src/lib/validators/compare/compare.validator.spec.ts, projects/forms/src/lib/validators/compare/compare.validator.ts, projects/forms/src/lib/validators/validators.ts, projects/layout/src/lib/pipes/item-size/item-size.pipe.spec.ts, projects/layout/src/lib/pipes/item-size/item-size.pipe.ts
This PR contains two commits.
This commit adds a compare validator that can compare child controls of a group by means of a provided comparator function.
This commit fixes existing layout item-size pipe unit tests & adds support for an undefined argument.
=> Feature/ngx forms/compare validator

apps/form-test/src/app/app.component.html, apps/form-test/src/app/app.component.ts, apps/form-test/src/date-input/date-input.component.html, libs/forms/README.md, libs/forms/package.json, libs/forms/src/lib/abstracts/custom-control-value-accessor/custom-control-value-accessor.ts, libs/forms/src/lib/abstracts/custom-control-value-accessor/index.ts, libs/forms/src/lib/abstracts/data-form/data-form.accessor.spec.ts, libs/forms/src/lib/abstracts/data-form/data-form.accessor.ts, libs/forms/src/lib/abstracts/form-accessor-container/form-accessor-container.ts, libs/forms/src/lib/abstracts/form/form.accessor.spec.ts, libs/forms/src/lib/abstracts/form/form.accessor.ts, libs/forms/src/lib/directives/errors/errors.directive.spec.ts, libs/forms/src/lib/utils/form-accessor/form-accessor.utils.ts
The previous implementation for the markAsTouched, markAsPristine and markAsDirty using the FormContainer approach had several downsides. 
- A FormContainer implementation was needed or it did not work
- Setting an individual control to touched/dirty/pristine did not work
This PR fixes the issues that were present in the earlier implementation, deprecates the older implementations, optimizes the code and streamlines the tests.
Due to the lack of a `updated` property in the `updateValueAndValidity`, there unfortunately is not a similar solution we can apply to this method and therefor we're still stuck with the current implementation.
=> fix(ngx-forms): Fix touched, dirty and pristine states for FormAccessors

libs/table/src/lib/table/ngx-table.component.html
When converting the table to the usage of Signals, we somehow missed getting the value of the tableCypressRecord signal.
=> feat(ngx-table): get signal value from cypressRecord

apps/layout-test/src/pages/main/main.component.ts, apps/layout-test/src/pages/secondary/secondary.component.html, apps/layout-test/src/tour/special-tour.component.scss, apps/layout-test/src/tour/tour.component.scss, libs/tour/README.md, libs/tour/src/lib/abstracts/tour-step/tour-step.component.ts, libs/tour/src/lib/services/tour-service/tour.service.ts, libs/tour/src/lib/types/tour.types.ts
Adds the following items:
- Now the clipPath of the backdrop works with window resizing, so the highlight will not stop working.
- Registering elements now works with events, so that the elements record gets updated correctly (and registers the first element when multiple items have the same tourItem tag)
- Extra data has been added to the tour step for further customization.
- The step now takes the cutout margin into account when rendering, so it does not overlap.
=> feat(ngx-tour): Add extra properties to step and make clipPath function with window resize

libs/tour/src/lib/services/tour-service/tour.service.ts
- Prevents the tour from crashing if there for some reason isn't a current step
- Always scroll back to the top before each step so that when we move back and forth during the tour, the look and feel is consistent.
=> fix(ngx-tour): Fix issue with inconsistent scroll behaviour and prevent issues with missing the currentStep

apps/layout-test/src/pages/main/main.component.ts, libs/tour/README.md, libs/tour/src/lib/services/tour-service/tour.service.ts
This fix will prevent the issue of the tourState being persistent when the tour closes before a manual closing trigger.
=> fix(ngx-tour): emit the closing events when the last element is not found

apps/layout-test/src/pages/main/main.component.html, apps/layout-test/src/pages/main/main.component.ts, libs/tour/README.md, libs/tour/src/index.ts, libs/tour/src/lib/mocks/index.ts, libs/tour/src/lib/mocks/overlay.mock.ts, libs/tour/src/lib/mocks/tour-holder.component.mock.ts, libs/tour/src/lib/mocks/tour-step.component.mock.ts, libs/tour/src/lib/operators/index.ts, libs/tour/src/lib/operators/use-mock-data-during-tour/use-mock-data-during-tour.operator.spec.ts, libs/tour/src/lib/operators/use-mock-data-during-tour/use-mock-data-during-tour.operator.ts, libs/tour/src/lib/services/tour-service/tour.service.spec.ts, libs/tour/src/lib/services/tour-service/tour.service.ts
This PR adds:
1.  An operator to show mock data when the tour is active
2. A slight delay before the tour starts to ensure that change detection has run
3. A visual update so the backdrop gets updated instead of deleted and recreated
=> feat(ngx-tour): Adds an operator to mock data when the tour is active, adds a delay and improves visuals

apps/layout-test/src/pages/main/main.component.ts, libs/tour/src/lib/services/tour-service/tour.service.ts
The `startTour` method did not emit when the tour had ended. This makes sure the `tourEnded` subject emits `Observable(undefined)` when the tour is aborted or finished.
https://github.com/studiohyperdrive/ngx-tools/assets/56075460/01a35125-c081-4e17-a0ea-6031bebe648d
=> fix(ngx-tour): make sure the startTour emits when the tour ends

libs/tour/src/lib/services/tour-service/tour.service.ts
The delay is added here to make sure the bounding box of the required element is calculated correctly. The issue that arose is displayed below.
https://github.com/user-attachments/assets/e90c28b9-326b-41de-aac2-c2236bef1389
=> fix(ngx-tour): add a delay after the beforeVisible of a tour step

README.md, apps/layout-test/src/app/app.component.ts, apps/layout-test/src/pages/mediaquery/mediaquery.component.ts, apps/layout-test/src/routes.ts, libs/utils/README.md, libs/utils/src/lib/services/index.ts, libs/utils/src/lib/services/media-query/mediaquery.service.ts, libs/utils/src/lib/services/media-query/query.service.md
This PR introduces a new service. It allows the user to provide one or more media queries whose changes will be emitted onto a stream. This stream can be subscribed to, but requires an id (the same that was used upon setting the query). If the id of the triggered breakpoint, the id of the triggered query will be emitted onto the stream. Those subscribers whose id matches the id that was pushed onto the stream, will be triggered and will receive the new query value (a boolean).
https://github.com/user-attachments/assets/d492f1ec-f169-413d-b5ac-eb7676ec120d
=> feat(ngx-layout): provide a service that allows subscribing to one or more media query

libs/utils/src/lib/pipes/with-router-links/with-router-links.md, libs/utils/src/lib/pipes/with-router-links/with-router-links.pipe.spec.ts, libs/utils/src/lib/pipes/with-router-links/with-router-links.pipe.ts, libs/utils/src/lib/types/with-router-links.types.ts
This addition will allow for a custom class to be defined onto the host of the new element through the injection context and the pipe arguments.
=> feat(ngx-utils): add a class to the withRouterLinks substitute element

libs/forms/src/lib/abstracts/custom-control-value-accessor/custom-control-value-accessor.ts
This PR fixes an issue when a ControlAccessor was used in a context without a parent control.
=> fix(forms): the custom-control-value-accessor will now throw a warning when no parent control was found

libs/forms/src/lib/validators/all-or-nothing-required/all-or-nothing-required.validator.ts, libs/forms/src/lib/validators/at-least-one-required/at-least-one-required.validator.ts, libs/forms/src/lib/validators/utils/form-error.util.ts, libs/utils/src/lib/pipes/has-values/has-values.pipe.ts, tsconfig.base.json
The `import * as clean from "obj-clean"` syntax was breaking ng18+ codebases that use the new application build system:
=> fix(utils|forms): an import of obj-clean was breaking production builds in codebases that use esModuleInterop with the application builder (ng18+)

libs/utils/README.md, libs/utils/package.json, libs/utils/src/lib/pipes/replace-elements/replace-elements.pipe.md, libs/utils/src/lib/pipes/replace-elements/replace-elements.pipe.spec.ts, libs/utils/src/lib/pipes/replace-elements/replace-elements.pipe.ts, libs/utils/src/lib/pipes/with-router-links/with-router-links.pipe.spec.ts, libs/utils/src/lib/providers/replace-elements/replace-elements.provider.ts, libs/utils/src/lib/tokens/index.ts, libs/utils/src/lib/tokens/replace-elements.token.ts, libs/utils/src/lib/types/index.ts, libs/utils/src/lib/types/replace-elements.types.ts
A more generic version of the WithRouterLinks pipe that now allows for any kind of WebComponent to be added
=> feat(ngx-utils): Add replace-elements pipe

apps/layout-test/src/pages/main/main.component.html, apps/layout-test/src/styles.scss, libs/tour/src/lib/mocks/overlay.mock.ts, libs/tour/src/lib/operators/use-mock-data-during-tour/use-mock-data-during-tour.operator.spec.ts, libs/tour/src/lib/services/tour-service/tour-server.spec.ts, libs/tour/src/lib/services/tour-service/tour.service.spec.ts, libs/tour/src/lib/services/tour-service/tour.service.ts
Upon starting the tour, a `ngx-tour-active` class is applied to the body. This allows for styling customisation like disabling pointer-events, for example.
https://github.com/user-attachments/assets/c7bd951f-9a54-40d7-811d-4161a3b9a0a4
=> feat(ngx-tour): add and remove a body class to allow for custom stying when the tour is active

libs/i18n/src/lib/guards/i18n/i18n.guard.spec.ts, libs/i18n/src/lib/guards/i18n/i18n.guard.ts, libs/i18n/src/lib/guards/set-language/set-language.guard.ts, libs/i18n/src/lib/services/root-i18n/root-i18n.service.ts
The SetLanguageGuard takes care of initializing the language when no language was set and this works perfectly when the language is not part of the route yet.
However, when the language parameter was already set, the guard is not called and the I18nGuard did not initialize the language. This PR fixes the issue.
=> fix(ngx-i18n): Add initializeLanguage

libs/inform/README.md, libs/inform/src/lib/services/modal/modal.service.ts
The datatype can be passed onto the data property of the modal. This allows for proper typing.
=> fix(ngx-inform): pass dataType onto modal data property

libs/inform/src/lib/services/modal/modal.service.ts
When the first ever modal is opened, the subject has not yet been initialised. It will therefore never open and aways throw the warning, as `!undefined?.close` is always `true`.
=> fix(modal.service): verify the subject is not undefined when checking if a modal exists

libs/inform/src/lib/services/modal/modal.service.ts, libs/inform/src/lib/types/modal.types.ts
The subscription got closed before emitting. This is resolved, along with added documentation of the modal interfaces.
https://github.com/user-attachments/assets/8d056ec1-6fb2-48d0-8046-5a78047917cc
=> fix(modalService): replace the subject with a behaviorSubject and document entities

apps/layout-test/src/app/app.component.ts, apps/layout-test/src/app/app.config.ts, apps/layout-test/src/modal/confirm.component.ts, libs/inform/src/lib/abstracts/modal/modal.abstract.component.ts, libs/inform/src/lib/services/modal/modal.service.ts, libs/inform/src/lib/types/modal.types.ts
https://github.com/user-attachments/assets/eec21667-a9f5-42cf-b595-6bf86d0207be
=> fix(ngx-inform): allow modal data set in the modal component to be emitted to the parent along with the type

apps/table-test/src/app/app.component.html, apps/table-test/src/app/app.component.ts, libs/table/README.md, libs/table/package.json, libs/table/src/lib/cell/cell.directive.ts, libs/table/src/lib/directives/has-focus-action/has-focus.directive.ts, libs/table/src/lib/directives/has-focus-action/index.ts, libs/table/src/lib/directives/index.ts, libs/table/src/lib/directives/tree-grid/index.ts, libs/table/src/lib/directives/tree-grid/tree-grid-row.directive.ts, libs/table/src/lib/directives/tree-grid/tree-grid.cell.directive.ts, libs/table/src/lib/directives/tree-grid/tree-grid.directive.ts, libs/table/src/lib/interfaces/index.ts, libs/table/src/lib/interfaces/tree-grid.types.ts, libs/table/src/lib/pipes/aria-sort/aria-sort.pipe.ts, libs/table/src/lib/pipes/index.ts, libs/table/src/lib/table/ngx-table.component.html, libs/table/src/lib/table/ngx-table.component.ts
Adds WCAG compliance through the [treegrid pattern. ](https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/)
Some form of Cypress/other related testing should be added in the future to properly test the keyboard interactions.
=> feat(ngx-table): Make the table accessible through the tree-grid pattern

apps/i18n-test/src/app/app.component.ts, apps/i18n-test/src/main.ts, libs/i18n/src/lib/guards/i18n/i18n.guard.spec.ts, libs/i18n/src/lib/guards/i18n/i18n.guard.ts, libs/i18n/src/lib/i18n.types.ts, libs/i18n/src/lib/services/root-i18n/root-i18n.service.ts
Allows for configuration to be set again whenever the user wants it.
=> feat(ngx-i18n): Add the ability to change the configuration when needed

libs/utils/README.md, libs/utils/package.json, libs/utils/src/lib/services/broadcast-channel/broadcast-channel.md, libs/utils/src/lib/services/broadcast-channel/broadcast-channel.service.spec.ts, libs/utils/src/lib/services/broadcast-channel/broadcast-channel.service.ts, libs/utils/src/lib/services/index.ts
This PR adds the `BroadcastChannelService` to the utils. This service wraps around the BroadcastChannel API:
https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API
=> feat(utils): the utils now contain a service that wraps around the BroadcastChannel API

libs/layout/src/lib/components/accordion/item/accordion-item.component.ts
The open state would not be toggled correctly, only after blur.
**Behaviour before:**
https://github.com/user-attachments/assets/ca8dafb0-d594-40c2-9fa9-7d8e620f47cf
**Behaviour after:**
https://github.com/user-attachments/assets/9b36283b-34b9-433b-9d95-667737d77754
=> fix(ngx-layout): update change detection as soon as an item is toggled

libs/angular/utils/src/lib/services/broadcast-channel/broadcast-channel.service.spec.ts
The mock for `runInBrowser` does not call the previously mocked `isBrowser`, instead align this mock with the method used by `initChannel`
=> fix(tests): adjust mock for new method

apps/cookies-test/project.json, apps/cookies-test/src/app/app.component.ts, apps/cookies-test/tsconfig.app.json
- Align project.json with its source (`apps/docs/project.json`)
- Fix syntax error in project.json
- Linting
- Add missing RouterModule
- Overwrite paths in tsconfig because this project also builds with ng-doc and outputs to a separate directory
=> fix(build): specify correct paths for ng-doc & ngx libs + linting

libs/angular/forms/src/lib/validators/date-range/date-range.validator.ts, libs/angular/forms/src/lib/validators/validators.ts
Default date formats of date validators were invalid formats. Corrected them so the validators work again when not providing a format
=> fix: wrong default date format

.github/workflows/deploy-docs.yml, apps/docs/project.json
Changing the baseHref in the project.json for the docs caused a refresh issue. To address this, the baseHref is now included only in the build command for the GitHub Pages deployment. This ensures the refresh functionality works correctly without breaking the deployment process.
=> fix(docs): reload on docs pages not working

.github/workflows/deploy-docs.yml
This PR resolves the issue with broken navigation on GitHub Pages. I attempted to remove the trailing slash using the Angular Router, but it seems the router does not apply when generating static HTML files for GitHub Pages.
If [this feature request](https://github.com/angular/angular-cli/issues/29173) every gets implemented, we should follow it's approach.
=> fix(docs): posible fix broken-navigation

libs/javascript/rxjs/src/lib/operators/fetch-if/fetch-if.operator.md, libs/javascript/rxjs/src/lib/operators/fetch-if/fetch-if.operator.spec.ts, libs/javascript/rxjs/src/lib/operators/fetch-if/fetch-if.operator.ts
The `fetchIf` operator now provides the data fetched from the source observable. This is useful when updating the state of the source observable and limits additional operators.
=> feat(js-rxjs): return the data of the source in every callback

apps/docs/src/app/pages/docs/angular/layout/implementation/components/index.md, apps/layout-test/src/pages/image-marker/image-marker.component.html, libs/angular/layout/src/lib/components/image-marker/image-marker.component.ts, libs/angular/layout/src/lib/services/image-marker/image-marker.service.ts, libs/angular/layout/src/lib/types/image-marker.types.ts
Allows us to pass the current zoom level and the possible zoom levels to the image marker
=> feat(ngx-layout): Allow zoom levels to be passed to the image-marker

libs/angular/i18n/src/lib/services/root-i18n/root-i18n.service.ts
`ngx-i18n` depended on `ngx-utils`, which is not allowed.
=> fix(ngx-i18n): Remove dependency on ngx-utils

.verdaccio/config.yml, apps/docs/src/app/categories/javascript/index.ts, apps/docs/src/app/categories/javascript/types/ng-doc.category.ts, apps/docs/src/app/pages/docs/javascript/types/authentication/index.md, apps/docs/src/app/pages/docs/javascript/types/authentication/ng-doc.page.ts, apps/docs/src/app/pages/docs/javascript/types/introduction/index.md, apps/docs/src/app/pages/docs/javascript/types/introduction/ng-doc.page.ts, libs/javascript/types/auth/.eslintrc.json, libs/javascript/types/auth/README.md, libs/javascript/types/auth/package.json, libs/javascript/types/auth/project.json, libs/javascript/types/auth/src/index.ts, libs/javascript/types/auth/src/lib/index.ts, libs/javascript/types/auth/src/lib/types/index.ts, libs/javascript/types/auth/src/lib/types/user.types.ts, libs/javascript/types/auth/tsconfig.json, libs/javascript/types/auth/tsconfig.lib.json, nx.json, package-lock.json, package.json, project.json, tsconfig.base.json
Sets up a library with shared authentication types that we can later use in shared authentication frontend packages
=> feat(js-types-auth): Setup authentication types package

apps/docs/src/app/pages/docs/angular/authentication/implementation/index.md, libs/angular/authentication/package.json, libs/angular/authentication/src/lib/index.ts, libs/angular/authentication/src/lib/interceptors/authentication/authentication.interceptor.spec.ts, libs/angular/authentication/src/lib/interceptors/authentication/authentication.interceptor.ts, libs/angular/authentication/src/lib/interceptors/index.ts, libs/angular/authentication/src/lib/mocks/authenticated-http-client.mock.ts, libs/angular/authentication/src/lib/mocks/index.ts, libs/angular/authentication/src/lib/providers/authentication-configuration.provider.ts, libs/angular/authentication/src/lib/services/authenticated-http-client/authenticated-http-client.service.spec.ts, libs/angular/authentication/src/lib/services/authenticated-http-client/authenticated-http-client.service.ts, libs/angular/authentication/src/lib/services/index.ts, libs/angular/authentication/src/lib/tokens/authentication-configuration.token.ts, libs/angular/authentication/src/lib/types/authentication-configuration.types.ts, libs/angular/authentication/src/lib/types/index.ts
Adds the `NgxAuthenticatedHttpClient` to the ngx-auth package.
=> feat(ngx-auth): Add interceptor and authenticated http client

apps/i18n-test/src/main.ts, libs/angular/i18n/src/lib/i18n.types.ts, libs/angular/i18n/src/lib/loader/multi-translation/multi-translation.loader.ts
This PR allows for a cache busting parameter to be appended to each translation file request. This allows the user more control over the private (browser) cache behaviour.
This can for example be paired with an automated build pipelines to always bust the cache when deploying a new version of the files. 
https://github.com/user-attachments/assets/a1df6645-fe83-4802-9b09-32d791a14a61
=> feat(ngx-i18n): add the option to cache bust the translation files using the root config

libs/javascript/pagination/src/hal-format.helper.spec.ts, libs/javascript/pagination/src/hal-format.helper.ts
Fixed an issue in `calculateNextPage` where it incorrectly allowed next page even if currentPage > totalPages. Now it returns the next page only if more pages exist. This improves the accuracy of HAL pagination and prevents broken next links.
=> Fix: correct next page logic in calculateNextPage utility

apps/docs/src/app/pages/docs/angular/table/implementation/context-row/demos/context-row-one/context-row-one.demo.component.html, apps/docs/src/app/pages/docs/angular/table/implementation/context-row/demos/context-row-one/context-row-one.demo.component.ts, apps/docs/src/app/pages/docs/angular/table/implementation/context-row/demos/context-row-three/context-row-three.demo.component.html, apps/docs/src/app/pages/docs/angular/table/implementation/context-row/demos/context-row-three/context-row-three.demo.component.scss, apps/docs/src/app/pages/docs/angular/table/implementation/context-row/demos/context-row-three/context-row-three.demo.component.ts, apps/docs/src/app/pages/docs/angular/table/implementation/context-row/demos/context-row-two/context-row-two.demo.component.html, apps/docs/src/app/pages/docs/angular/table/implementation/context-row/demos/context-row-two/context-row-two.demo.component.ts, apps/docs/src/app/pages/docs/angular/table/implementation/context-row/demos/index.ts, apps/docs/src/app/pages/docs/angular/table/implementation/context-row/index.md, apps/docs/src/app/pages/docs/angular/table/implementation/context-row/ng-doc.page.ts, apps/table-test/src/app/app.component.html, apps/table-test/src/app/app.component.scss, apps/table-test/src/app/app.component.ts, apps/table-test/src/main.ts, libs/angular/table/src/lib/table/ngx-table.component.html, libs/angular/table/src/lib/table/ngx-table.component.scss, libs/angular/table/src/lib/table/ngx-table.component.ts, libs/angular/table/src/lib/token/ngx-table-config.token.ts
The table has gotten an upgrade!
We required a context row for the VLAIO project and saw no other practical way than to add it as a feature to the table.
In short: a context row is a row that adds no accessibility addition, will always be interpreted as if it was a `span` element. The text in it will be read, buttons and links will have their persisting accessibility features, and an additional row is added to the table. This row allows for a more customisable experience, like the one in the styled example of the docs. (added as PDF to the attachments)
It uses an input and is therefore toggleable. It uses keys defined in the data object array to evaluate whether a row requires an additional context header.
**PDF of the docs:** …
=> feat(ngx-table): add an optional context row to the table
